//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cse460projectBMICalculator.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BMI_value", ReplyAction="http://tempuri.org/IService1/BMI_valueResponse")]
        double BMI_value(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BMI_value", ReplyAction="http://tempuri.org/IService1/BMI_valueResponse")]
        System.Threading.Tasks.Task<double> BMI_valueAsync(int height, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HealthIndicator_value", ReplyAction="http://tempuri.org/IService1/HealthIndicator_valueResponse")]
        string HealthIndicator_value(double BMI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HealthIndicator_value", ReplyAction="http://tempuri.org/IService1/HealthIndicator_valueResponse")]
        System.Threading.Tasks.Task<string> HealthIndicator_valueAsync(double BMI);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : cse460projectBMICalculator.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<cse460projectBMICalculator.ServiceReference1.IService1>, cse460projectBMICalculator.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double BMI_value(int height, int weight) {
            return base.Channel.BMI_value(height, weight);
        }
        
        public System.Threading.Tasks.Task<double> BMI_valueAsync(int height, int weight) {
            return base.Channel.BMI_valueAsync(height, weight);
        }
        
        public string HealthIndicator_value(double BMI) {
            return base.Channel.HealthIndicator_value(BMI);
        }
        
        public System.Threading.Tasks.Task<string> HealthIndicator_valueAsync(double BMI) {
            return base.Channel.HealthIndicator_valueAsync(BMI);
        }
    }
}
